root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/nanonet-backend ./cmd/main.go"
  bin = "./tmp/nanonet-backend"
  full_bin = "./tmp/nanonet-backend"
  include_ext = ["go"]
  exclude_dir = ["vendor", "testdata"]
  delay = 500
  kill_delay = "500ms"
  rerun = false

[log]
  time = false
  main_only = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
